name: Main

on: push

jobs:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-of-jobsjob_idsteps
  build-and-run:
    name: Main
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          # auto-activate-base: true
          activate-environment: "moco"
          python-version: "3.11"

      - name: Install opensim-moco package
        run: conda install -c opensim-org opensim-moco

      - name: List files in the repository
        run: ls -la
        
      - name: Run Python script
        run: python exampleMocoTrack.py
