name: Main

on: push

jobs:
  build-and-run:
    name: Main
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set commit name and date
      #   id: configure
      #   run: |
      #     echo "COMMIT_NAME=$(git log -1 --format=%h)" >> $GITHUB_ENV
      #     echo "COMMIT_DATE=$(git log -1 --format=%cd --date=format:'%Y-%m-%d')" >> $GITHUB_ENV

      # - name: Get short SHA
      #   run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # - name: Get Date
      #   run: echo "DATE=$(Get-Date -Format "yyyyMMdd")" >> $GITHUB_ENV

      # - name: Output Run ID
      #   run: echo ${{ github.run_id }}
      # - name: Output Run Number
      #   run: echo ${{ github.run_number }}
      # - name: Output Run Attempt
      #   run: echo ${{ github.run_attempt }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: 'moco'
          python-version: '3.11'
          # miniforge-version: 'latest'
          # use-mamba: true

      - name: Install opensim-moco package
        run: conda install -c opensim-org opensim-moco
        # run: mamba install -c opensim-org opensim-moco --yes

      - name: Run OpenSim Moco script
        run: python exampleMocoTrack.py

      - name: List files in the repository
        run: dir

      - name: Upload Moco solution file
        uses: actions/upload-artifact@v4
        with:
          name: Moco-Solution-${{ github.run_number }}
          path: 'MocoStudy_solution.sto'
